# .github/workflows/security-checks.yml
name: Security Checks

# Defines when the action will run
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      # Check out your repository
      - uses: actions/checkout@v2

      # Scan for secrets accidentally committed
      - name: TruffleHog Security Scan
        uses: trufflesecurity/trufflehog-actions-scan@master
        with:
          path: ./
          base: main
          head: HEAD

      # Dependency scanning (if you're using Node.js)
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run npm audit
        run: npm audit
