# .github/workflows/security-checks.yml
name: Security Checks

# Defines when the action will run
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      # WHAT: Check out your repository
      # WHY: Required for any workflow that needs to access repo files	
      - uses: actions/checkout@v3	# Updated from v2 to v3

      # WHAT: Scan for secrets accidentally committed
      # WHY: Prevents sensitive info from being exposed in repo(exposed secrets=breaches)
      # Updated TruffleHog action
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
	  # Remove base and head parameters as they're not needed for full repo scan
	  extra_args: --only-verified

      # WHAT: Dependency scanning (if you're using Node.js)
      # WHY: Required if running npm commands or node.js security tools
     # - name: Setup Node.js
       # uses: actions/setup-node@v3	# Updated from v2 to v3
       # with:
         # node-version: '16'
          
     # - name: Install dependencies
       # run: npm ci
        
      # WHAT: Checks dependencies for known vulnerabilities
      # WHY: Ensures you're not using packages with known security issues
     # - name: Run npm audit
       # run: npm audit
